<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Dummy_m extends CI_Model
{

    public $table = 'detail_cproduk';
    public $id = 'id_cproses';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get data ri minimal
    function get_by_min_ri()
    {
        $this->db->order_by('ri', 'ASC');
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_cproses', $q);
	$this->db->or_like('id_produk', $q);
	$this->db->or_like('id_mesin', $q);
	$this->db->or_like('urutan_proses', $q);
	$this->db->or_like('ci', $q);
	$this->db->or_like('ti', $q);
	$this->db->or_like('ri', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_cproses', $q);
	$this->db->or_like('id_produk', $q);
	$this->db->or_like('id_mesin', $q);
	$this->db->or_like('urutan_proses', $q);
	$this->db->or_like('ci', $q);
	$this->db->or_like('ti', $q);
	$this->db->or_like('ri', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Dummy_m.php */
/* Location: ./application/models/Dummy_m.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-15 01:39:23 */
/* http://harviacode.com */