<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Hasil_m extends CI_Model
{

    public $table = 'hasil';
    public $id = 'id_proses';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get untuk cetak
    function get_cetak()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->join('produk', 'produk.id_produk = hasil.id_produk');
        $this->db->join('mesin', 'mesin.id_mesin = hasil.id_mesin');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    function get_by_prosesb4($job,$proses,$mesin)
    {
        $this->db->or_like('id_produk', $job);
        $this->db->or_like('urutan_proses', $proses);
        $this->db->or_like('id_mesin', $mesin);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->row();
    }

    function select_max()
    {
        $this->db->select_max('rj');
        return $this->db->get($this->table)->result();
    }

    function get_by_mesin($mesin)
    {
        $this->db->like('id_mesin', $mesin);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
       /* $this->db->like('', $q);*/
    $this->db->like('id_proses', $q);
    $this->db->or_like('id_produk', $q);
    $this->db->or_like('urutan_proses', $q);
    $this->db->or_like('id_mesin', $q);
    $this->db->or_like('ci', $q);
    $this->db->or_like('ti', $q);
    $this->db->or_like('rj', $q);
    $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
       /* $this->db->like('', $q);*/
    $this->db->like('id_proses', $q);
    $this->db->or_like('id_produk', $q);
    $this->db->or_like('urutan_proses', $q);
    $this->db->or_like('id_mesin', $q);
    $this->db->or_like('ci', $q);
    $this->db->or_like('ti', $q);
    $this->db->or_like('rj', $q);
    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // get detail
    function get_detail($limit, $start = 0, $q = NULL)
    {   
        $this->db->order_by($this->id, $this->order);
    $this->db->like('hasil.id_proses', $q);
    $this->db->or_like('hasil.id_produk', $q);
    $this->db->or_like('hasil.urutan_proses', $q);
    $this->db->or_like('hasil.id_mesin', $q);
    $this->db->or_like('hasil.ci', $q);
    $this->db->or_like('hasil.ti', $q);
    $this->db->or_like('hasil.rj', $q);
    $this->db->join('produk', 'produk.id_produk = hasil.id_produk');
    $this->db->join('mesin', 'mesin.id_mesin = hasil.id_mesin');
    $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }


    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Hasil_m.php */
/* Location: ./application/models/Hasil_m.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-07 17:01:50 */
/* http://harviacode.com */

