<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Metode_m extends CI_Model
{

    public $table = 'detail_produk';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by process
    function get_by_process($noproses)
    {
        $this->db->where('urutan_proses', $noproses);
        return $this->db->get($this->table)->result();
    }

    // get data by process dan by id_produk sesuai tanggal jadwal
    function get_by_awal_tanggal($tgl)
    {
        $params = $this->db->query("SELECT * FROM detail_produk, penjadwalan WHERE detail_produk.urutan_proses = '1' AND penjadwalan.id_produk = detail_produk.id_produk AND penjadwalan.tanggal = '$tgl'");
        return $params->result();

    }

    function get_by_tanggal($tgl)
    {
        $params = $this->db->query("SELECT * FROM detail_produk, penjadwalan WHERE penjadwalan.id_produk = detail_produk.id_produk AND penjadwalan.tanggal = '$tgl'");
        return $params->result();
    }


    // get next process
    function get_next_process($job, $proses)
    {
        $this->db->where('id_produk', $job);
        $this->db->where('urutan_proses', $proses);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_produk', $q);
	$this->db->or_like('id_mesin', $q);
	$this->db->or_like('urutan_proses', $q);
	$this->db->or_like('t_proses', $q);
	$this->db->or_like('t_all', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_produk', $q);
	$this->db->or_like('id_mesin', $q);
	$this->db->or_like('urutan_proses', $q);
	$this->db->or_like('t_proses', $q);
	$this->db->or_like('t_all', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // update by id_produk
    function update_by_idproduk($id, $total)
    {
        $this->db->where('id_produk', $id);
        $this->db->update('t_all', $total);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Metode_m.php */
/* Location: ./application/models/Metode_m.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-15 01:38:59 */
/* http://harviacode.com */